services:
  - type: web
    name: ocr-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api/app.py
    autoDeploy: true
    branch: master

  - type: web
    name: monitoring-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python monitoring/app.py
    autoDeploy: true
    branch: master
